services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "scoi_user"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "scoi_db"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: